### PR TITLE
otterdog: allow members to create teams

### PR DESCRIPTION
**Pull request by ltekieli**

### CODE REVIEW

**Comment by ltekieli** [comment]
@netomi is it forbidden to allow members to create organization teams?

image

**Comment by netomi** [comment]
yeah, so far we have the policy that teams can not be created by members themselves. We can set them up if needed.
The reason for this is because of the inheritance rules of teams. You could create a sub-team of project-leads and that sub-team would inherit the permissions of the project-leads.

**Comment by ltekieli** [comment]
@netomi thanks for the clarification

@antonkri FYI.

**Comment by antonkri** [comment]
@netomi should we create a ticket for you for creation of the teams and if yes, where?

**Comment by netomi** [comment]
The EF HelpDesk is the right place: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new

**Comment by antonkri** [comment]
> The EF HelpDesk is the right place: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new

Done: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5438

**Pull request closed without merging**
