### PR TITLE
otterdog: add repositories for integration setup

### PR DESCRIPTION
**Pull request by ltekieli**
Repositories mandatory for the integration setup:
- https://eclipse-score.github.io/score/features/integration/index.html

### CODE REVIEW

**Review by antonkri — APPROVED** [review]

**Comment by netomi** [comment]
for auto-merging to be enabled the PR needs to be approved by a PL for now.
Once its eligible a comment will be added.

**Review by grandyholger — APPROVED** [review]
LGTM

**Comment by ltekieli** [comment]
@netomi can you please approve and merge this PR, @grandyholger  does not have yet correct github setup for the PL approve to kick in.

**Comment by netomi** [comment]
@grandyholger already got the invitation, you just need to accept it.

But I can approve and merge anyways, at some point we would like to allow project to define how they want that configuration changes to be approved. Some project really want a PL to approve e.g. requests for new repos.

**Pull request merged**
